Repository kreuzwerker/terraform-provider-docker, pull requests merged in 2021-06, with the labels that each got.

#213 docs: fix typos in docker_image example usage
  templates/resources/image.md.tmpl
Labels: documentation

#216 docs: fix few typos
  CONTRIBUTING.md
  templates/resources/image.md.tmpl
Labels: documentation

#223 internal/provider: include image name in error message
  internal/provider/data_source_docker_registry_image.go
Labels: d/registry_image, r/registry_image

#227 fix/service delete deadline
  docs/resources/service.md
  go.mod
  go.sum
  internal/provider/helpers.go
  internal/provider/resource_docker_container_funcs.go
  internal/provider/resource_docker_network_funcs.go
  internal/provider/resource_docker_service.go
  internal/provider/resource_docker_service_funcs.go
  internal/provider/resource_docker_service_test.go
  internal/provider/resource_docker_volume.go
Labels: r/service

#235 docs: update readme
  CONTRIBUTING.md
  README.md
  assets/docker-logo.png
  assets/terraform-logo.png
  assets/xw-logo.png
Labels: documentation

#230 fix: Update the URL of the docker hub registry
  docs/index.md
  examples/provider/provider-credentials.tf
  internal/provider/data_source_docker_registry_image.go
  internal/provider/resource_docker_image_funcs.go
  internal/provider/resource_docker_registry_image_funcs.go
Labels: bug
