Repository kreuzwerker/terraform-provider-docker, pull requests merged in 2021-03, with the labels that each got.

#119 chore: bump docker dependency to v20.10.5
  docker/resource_docker_container_funcs.go
  docker/resource_docker_service.go
  docker/resource_docker_service_funcs.go
  docker/structures_service.go
  go.mod
  go.sum
  website/docs/r/service.html.markdown
Labels: breaking change

#140 feat: support darwin arm builds and golang 1.16
  .github/workflows/acc-test.yaml
  .github/workflows/compile.yaml
  .github/workflows/release.yaml
  .github/workflows/unit-test.yaml
  .github/workflows/website-lint.yaml
  .go-version
  GNUmakefile
  go.mod
  scripts/compile.sh
Labels: enhancement

#149 docs: add a guide about writing issues to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#158 docs: add an example to build an image with docker_image
  website/docs/r/image.html.markdown
Labels: documentation, r/image

#159 docs: format `Guide of Bug report` for readability
  CONTRIBUTING.md
Labels: documentation

#151 fix: search local images with Docker image ID
  internal/provider/resource_docker_image_funcs.go
  internal/provider/resource_docker_image_test.go
Labels: bug, r/image
